- name: configure jenkins scheduler
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    JENKINS_EXTRA_PKGS:
      - libmysqlclient-dev
      - mysql-client
      - zip
  roles:
    - python
    - s3cmd
    - jenkins
  tasks:
    - name: Checkout analytics configuration
      sudo_user: jenkins
      git: >
        dest=/home/jenkins/analytics-configuration
        repo={{ analytics_configuration_repo }}
        version={{ analytics_configuration_version }}

    - name: Checkout analytics pipeline
      sudo_user: jenkins
      git: >
        dest=/home/jenkins/analytics-tasks
        repo={{ analytics_pipeline_repo }}
        version={{ analytics_pipeline_version }}
